[workspace]
members = [
    "programs/*"
]
resolver = "2"
[replace]
"ahash:0.8.11" = { path = "vendor/ahash" }

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

